# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13fe6a7b7a3ea1e68dcb875441bf6f6fcd4da1a8d5d65edd40bafd2bd39d302e25d3d7285d9f70c5b4c9af5bf478914615e7e92f32176c663a9d0b2caf5ea2c6

test:
  secret_key_base: 90634554c5397b5e036b2405493db259fe2886b8dff8a186569f37c6dc2fd82670ebb63f2731f449bf8a1cfd6d995275f1723044ac16f208d55f0b3c6f38b32f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
